### ISSUE TITLE
Allow for tags in source view

### ISSUE THREAD

**Issue by chrisbulmer** [SourceKettle/sourcekettle#136]

**Comment by antineutron** [comment]
branches containing a / also don't work at all (the easy way to display tags is to display the branch tags/tag-name). This also breaks compatibility with git-flow, which is annoying.

The branch will have to be passed as a query string parameter. The current method of routing ....../:branch/path... won't work if branches can have multiple / separated parts and so can filenames, especially if we can miss out the branch completely and default to 'master' (what if there's a file or directory called 'master'? etc)
