### ISSUE TITLE
Closing Ticket UI inconsistent

### ISSUE THREAD

**Issue by cgutteridge** [SourceKettle/sourcekettle#406]
If you close a ticket using 'close' or 'resolved' buttons it makes you go via a second screen which forces you to enter some explanation text and click the button again.

However you can close a ticket using the drag-and-drop so this enforcement is ineffective.

Could we maybe make a configuration option for 'require explanation when closing ticket'? If we did we would need to ask for the explanation in the drag & drop interface too.

**Comment by antineutron** [comment]
Removed in dev.
