### ISSUE TITLE
Swimlanes+Icebox much bigger than a laptop screen

### ISSUE THREAD

**Issue by cgutteridge** [SourceKettle/sourcekettle#413]
This makes it hard to drag something to the icebox.
Proposed solution: After page load or resize test the hight of swimlanes+icebox. If they are more than the height of the window, use jquery to resize them to something sensible and add overflow: scroll

**Comment by antineutron** [comment]
Can you take a look at the ECS dev site and see if it looks OK? The columns are now scrollable.

**Comment by cgutteridge** [comment]
Sure, but I'll need a link.

**Comment by antineutron** [comment]
Removed lots of unuseful whitespace and made the sidebar collapse on small screens. Also added a "no distractions" toggle button that hides/shows the sidebar and title.
