### ISSUE TITLE
Add more information to the milestone Kanban

### ISSUE THREAD

**Issue by patrickmcsweeney** [SourceKettle/sourcekettle#460]
Is it possible to replace the bit where it says "Story points 8/43" with the progress bar from the cover the milestone (image attached). It doesnt have to be that but something which lets to see a summary of how many story points are in each column would be ideal.

![the_progress_bar](https://cloud.githubusercontent.com/assets/1313219/6465467/36ced776-c1b9-11e4-94f5-963adef395d6.PNG)

**Comment by antineutron** [comment]
Yeah, that should be doable
