### ISSUE TITLE
No way to get back from 'create item'

### ISSUE THREAD

**Issue by cgutteridge** [SourceKettle/sourcekettle#466]
When the create task page reloads and lets you have another task, IF the just submitted task had a workflow (ie. there's one set on the form), put a button to take you to that milestone.

**Comment by antineutron** [comment]
Depends on your situation. If you've created a new milestone, and you want to add a pile of tasks to it, the current behaviour is more useful.

There's already a link to the task itself in the flash message that appears at the top of the screen - might just add another link to the milestone if it exists (I've had this annoyance a few times myself!)
