### ISSUE TITLE
Zero story points

### ISSUE THREAD

**Issue by rprince** [SourceKettle/sourcekettle#467]
When creating a task, it is possible to set a value of zero story points.

However, when clicking [-] 0 [+] buttons on the task view page, it's impossible to get to zero story points. Once you click [+] to move from 0 to 1, then the [-] stops you going back!

Presumably this needs some validation in the original task creation form?

**Comment by rprince** [comment]
PS. The reason I wanted zero story points, is because I was creating a top-level story, that my other stories were "subtask of/block", so I was half expecting the parent story points to be the sum of the subtask story points.

**Comment by antineutron** [comment]
I vaguely recall spotting this then forgetting about it...

I think it was tricky to fix (something like if you sent an update via 
an API call, if it was missing the story points field, that was handled 
in the same way as setting it to zero, which caused trouble - I forget 
why it wasn't a simple fix, maybe I just hadn't had my coffee yet...)

**Comment by antineutron** [comment]
turned out it *was* a simple fix... it's a dumb check in the javascript, not the backend
