### ISSUE TITLE
Order of assignees

### ISSUE THREAD

**Issue by patrickmcsweeney** [SourceKettle/sourcekettle#475]
When you click on the pull down to assign the ticket it is not clear what the ordering is of the list. When you add a group to the project the list is quite long. It would be helpful if it was alphabetical by first name.
![assignees](https://cloud.githubusercontent.com/assets/1313219/7980956/a1350d5a-0aa3-11e5-8b92-a546be1e7eb4.PNG)

**Comment by antineutron** [comment]
Yeah, I think the ordering is arbitrary. Will fix to be less dumb.

It'd be good to work out how to deal with the whole team thing as well. 
If you've got a large team on a lot of projects, the list gets long. 
Maybe an easy way to add team members as direct collaborators would 
help, then only show direct collaborators in the list.

**Comment by patrickmcsweeney** [comment]
Nah i think the list being long is only a problem because you have to hunt
through it. There is a little bug that when it gets mega long it goes off
the bottom of the screen but we can create a seperate issue for that.

Patrick

On Thu, Jun 4, 2015 at 11:05 AM, Andy Newton <notifications@github.com>
wrote:

> Yeah, I think the ordering is arbitrary. Will fix to be less dumb.
>
> It'd be good to work out how to deal with the whole team thing as well.
> If you've got a large team on a lot of projects, the list gets long.
> Maybe an easy way to add team members as direct collaborators would
> help, then only show direct collaborators in the list.
>
> On 04/06/2015 10:22, Patrick McSweeney wrote:
> >
> > When you click on the pull down to assign the ticket it is not clear
> > what the ordering is of the list. When you add a group to the project
> > the list is quite long. It would be helpful if it was alphabetical by
> > first name.
> > assignees
> > <
> https://cloud.githubusercontent.com/assets/1313219/7980956/a1350d5a-0aa3-11e5-8b92-a546be1e7eb4.PNG
> >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/SourceKettle/sourcekettle/issues/475>.Web Bug from
> >
> https://github.com/notifications/beacon/AAdY-iPNn40A9sANmn-L9KFVtbnLpwR7ks5oQBBlgaJpZM4E35RF.gif
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SourceKettle/sourcekettle/issues/475#issuecomment-108820814>
> .
>



-- 

'But your intentions are beside the point, It's the outcome of your actions
that count...'
